# Bagian I: Python Intro

## 1. Apakah Python?

Python adalah bahasa pemrograman tingkat tinggi (*high-level*) untuk kebutuhan program secara umum. Python adalah bahasa yang terinterpretasi, yaitu tanpa melalui proses *compile* seperti pada C atau C++. Kode pada Python akan dibaca baris per baris dan dijalankan oleh *interpreter*. *Script* Python memiliki ekstensi .py secara konvensional. File ini berisi kode-kode yang akan dieksekusi ketika dipanggil.

Python dirancang untuk memudahkan pemrograman, dengan mengutamakan keterbacaan (*readability*) yang diantaranya ditunjukkan dalam penggunaan indentasi untuk memisahkan blok-blok kode dan sederhana secara sintaks. Hal ini kontras dengan bahasa pemrograman lain yang biasanya menggunakan tanda kurung sebagai pemisah.

## 2. Mengapa Python?

#### Pro
1. Mudah
Salah satu kelebihan Python yang sering diunggulkan adalah kemudahan dan kesederhanaannya. Sebagai contoh, kita akan membuat program untuk menampilkan barisan Fibonacci dalam bahasa C dan Python.
Dalam C:
```c
#include <stdio.h>
int main()
{
    int i, n, t1 = 0, t2 = 1, nextTerm;
    printf("Enter the number of terms: ");
    scanf("%d", &n);
    printf("Fibonacci Series: ");
    for (i = 1; i <= n; ++i)
    {
        printf("%d, ", t1);
        nextTerm = t1 + t2;
        t1 = t2;
        t2 = nextTerm;
    }
    return 0;
}
```
dan dalam Python:
```python
def fib(n):
    if n < 2:
        return n
    return fib(n-2) + fib(n-1)
```
Penulisan dalam C membutuhkan 16 baris, sedangkan dalam Python hanya membutuhkan 4 baris. Ini menunjukkan bahwa Python lebih sederhana dalam penggunaannya.
2. Lengkap
Python memiliki modul-modul yang lengkap, yang dapat memenuhi kebutuhan pemrograman kita secara umum. Modul-modul yang dimaksud adalah modul komputasi numerik, simbolik, jaringan komputer, GUI, software bisnis dll.
3. Multiplatform
Python tersedia untuk berbagai macam sistem termasuk Windows, Linux dan macOS, dan untuk bermacam arsitektur, mulai dari Intel, Power, dan ARM.
4. Umum
Python dapat digunakan untuk hampir semua masalah komputasi tingkat tinggi; desktop, mobile, web, cloud, sains, dll.

#### Kontra
1. Kecepatan
Salah satu kelemahan Python yang sering disoroti adalah kecepatannya yang cukup rendah bila dibandingkan dengan C atau C++. Hal ini dikarenakan Python adalah bahasa terinterpretasi. Tetapi masalah ini masih dapat ditoleransi karena Python cukup mudah dalam penggunaannya. Selain itu, kemudahan Python dan kecepatan C dapat diperoleh dengan Cython, yaitu bahasa Python yang terkompilasi.

## 3. Instalasi

### Native

1. Download installer terbaru dari python.org
2. Install
3. Buka command line, lalu ketikkan `>>> python`
4. Ketikkan perintah `>>> version()`

### Docker

1. Download Docker Windows dari (https://store.docker.com/editions/community/docker-ce-desktop-windows)
2. Install Docker
3. Buka command line, ketikkan perintah `> docker run -it -p 8888:8888 tensorflow/tensorflow:latest`

### Package Manager `pip`

`pip` adalah manajer aplikasi Python. Dengan `pip` kita dapat menginstall aplikasi-aplikasi tambahan untuk Python. Misal untuk kebutuhan komputasi numerik, kita membutuhkan Numpy. Dengan `pip`, eksekusi perintah `> pip install numpy`

## 4. Contoh Penggunaan

### Dasar

Contoh program sederhana dalam Python adalah program fungsi faktorial. Fungsi faktorial ditulis sebagai $n!$, yang didefinisikan $$n!=n\cdot (n-1) \cdot (n-2) \ldots 3 \cdot 2 \cdot 1$$ atau secara rekursif bisa dinyatakan sebagai $$n!=n\cdot (n-1)!.$$ Secara konvensi $0!=1$ dan $1!=1$. Hubungan rekursif ini dalam Python dapat ditulis sebagai:
```python
def faktorial(n):
    if n==0:
        return 1
    else:
        return n * faktorial(n-1)
```

### Numerik

In [21]:
import numpy as np
A = np.random.randint(low=0, high=199, size=(300,300))
B = np.random.randint(low=0, high=199, size=(300,800))

In [22]:
# Pendefinisian matriks elemen random A dan B
A,B

(array([[115,  28, 105, ...,  40,   1, 142],
        [ 45,  34,  73, ...,   4,  82,  28],
        [ 89,  23, 102, ..., 191, 176,  67],
        ..., 
        [ 43,  35, 193, ..., 139,  52, 108],
        [100,  11, 102, ...,  39, 136,   1],
        [119,  31,  10, ..., 158, 101, 176]]),
 array([[ 40, 106,  31, ...,  90,  70, 115],
        [ 65,  27, 118, ...,  31,  54, 115],
        [ 49,  69,  61, ..., 185,  71,  51],
        ..., 
        [ 88,   8,  42, ...,  13, 135, 171],
        [115,  92, 110, ..., 169,  97, 120],
        [ 27, 100,  71, ...,  57, 190, 174]]))

In [23]:
# Perkalian dot A dan B hanya 130 ms
%time np.dot(A,B)

CPU times: user 130 ms, sys: 0 ns, total: 130 ms
Wall time: 134 ms


array([[3027918, 3051807, 2936616, ..., 2763545, 2859813, 2996294],
       [3104186, 3071974, 3143282, ..., 2893758, 2900737, 2926660],
       [3227117, 3198823, 3180015, ..., 2915252, 3000203, 3165277],
       ..., 
       [2986800, 3001458, 2906561, ..., 2700080, 2844170, 2993051],
       [3166906, 3049911, 3041952, ..., 2776476, 2824559, 2981969],
       [3052893, 2955579, 2934603, ..., 2748705, 2947889, 2977434]])

In [24]:
# invers dari matriks A hanya 30 ms
%time np.linalg.inv(A)

CPU times: user 30 ms, sys: 10 ms, total: 40 ms
Wall time: 35.3 ms


array([[  7.14739820e-04,  -5.92778343e-04,   3.91693339e-04, ...,
         -6.30683892e-04,   4.92710123e-04,   3.68004569e-04],
       [  2.16218256e-05,  -2.63941450e-05,  -4.27559891e-04, ...,
         -7.91905596e-04,   5.28484002e-04,  -1.70150976e-04],
       [ -1.45213596e-04,   2.46988149e-04,   9.37026403e-05, ...,
         -1.74788179e-04,   1.00855984e-03,  -1.69016097e-04],
       ..., 
       [  1.29642550e-05,  -1.79901496e-04,   2.64307080e-04, ...,
          1.49865074e-04,   3.03506383e-04,  -1.43134602e-04],
       [  4.02898997e-04,  -8.19990620e-04,  -1.23426010e-03, ...,
         -2.06282727e-03,  -2.71884452e-04,   4.90955854e-04],
       [  2.66003181e-04,  -2.57650709e-04,   6.24100626e-04, ...,
         -1.43545000e-04,   5.22820854e-05,   7.85939732e-04]])

In [25]:
C = np.random.randint(low=0, high=5990, size=(6000,6000))

In [26]:
C

array([[1570, 1593, 4664, ..., 1873, 3520,  379],
       [2547, 1279,  486, ...,  245, 2376, 1836],
       [ 479, 2458, 4410, ..., 2595, 5953,   17],
       ..., 
       [1487, 5012, 3984, ...,  588,  335, 2543],
       [ 294, 5648, 1158, ..., 2000, 3805, 4599],
       [3096, 3865, 4893, ..., 4219,  904, 5185]])

In [27]:
# Waktu komputasi invers matriks 6000 x 6000 adalah 20.8 detik !
%time np.linalg.inv(C)

CPU times: user 20.8 s, sys: 2.05 s, total: 22.9 s
Wall time: 12.8 s


array([[  1.19248835e-05,  -4.97853756e-05,  -1.22476557e-05, ...,
         -1.22616621e-05,   3.62797306e-05,   5.64686843e-05],
       [ -4.94969372e-06,  -1.96843004e-05,  -9.87242935e-06, ...,
         -5.29448385e-06,   1.29346837e-05,   1.77157636e-05],
       [ -8.40123592e-06,  -3.07930310e-06,  -2.83304396e-06, ...,
         -1.48251317e-06,  -5.38864353e-06,   1.75679275e-06],
       ..., 
       [  1.33488522e-05,   1.66189078e-05,   1.37898552e-05, ...,
          3.01491501e-06,  -2.58385066e-06,  -1.10241673e-05],
       [  1.32902317e-05,   8.33130978e-06,   6.67304310e-06, ...,
          2.92861905e-06,   2.73194388e-06,  -6.29668613e-06],
       [ -1.87917218e-05,   3.11450749e-05,   5.57834241e-06, ...,
          8.13136063e-06,  -2.06622400e-05,  -4.13933348e-05]])

In [32]:
# Matriks yang tidak mempunyai invers
D = np.matrix([[2,4],[1,2]])
np.linalg.inv(D)

LinAlgError: Singular matrix

### Simbolik

In [37]:
# Komputasi simbolik menggunakan SymPy
from sympy import Symbol
x = Symbol('x')
y = Symbol('y')

In [38]:
# Pengurangan
2 * x - x

x

In [41]:
# Perkalian
2*y*y

2*y**2

In [46]:
from sympy import Symbol , exp , sin , cos , sqrt , diff

Turunan parsial berikut akan dihitung $\frac{\partial}{\partial{y}}\sin{x}$, $\frac{\partial}{\partial{x}}\sin{y}$, dan $\frac{\partial}{\partial{x}}\sin{x}\cos{y}$

In [48]:
# Turunan Parsial
diff(sin(x),y), diff(sin(y),x), diff((sin(x)*cos(y)),x)

(0, 0, cos(x)*cos(y))

### Statistika

In [44]:
diff(x**2,x,x)

2

### Plot